CREATE TYPE "UserRole" AS ENUM (
  'admin',
  'employer',
  'candidate'
);

CREATE TYPE "UserStatus" AS ENUM (
  'pending',
  'active',
  'suspended',
  'rejected'
);

CREATE TYPE "JobStatus" AS ENUM (
  'draft',
  'open',
  'closed'
);

CREATE TYPE "EmploymentType" AS ENUM (
  'full_time',
  'part_time',
  'contract',
  'internship',
  'freelance'
);

CREATE TYPE "ExperienceLevel" AS ENUM (
  'junior',
  'mid',
  'senior',
  'lead'
);

CREATE TYPE "ApplicationStatus" AS ENUM (
  'pending',
  'reviewed',
  'shortlisted',
  'interview',
  'accepted',
  'rejected'
);

CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "email" varchar UNIQUE,
  "password" varchar,
  "role" "UserRole",
  "status" "UserStatus",
  "email_verified_at" timestamp,
  "remember_token" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "candidate_profiles" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint UNIQUE,
  "phone" varchar,
  "date_of_birth" date,
  "country" varchar,
  "city" varchar,
  "headline" varchar,
  "bio" text,
  "github_url" varchar,
  "linkedin_url" varchar,
  "portfolio_url" varchar,
  "resume_path" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "employer_profiles" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint UNIQUE,
  "company_id" bigint,
  "phone" varchar,
  "position" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "companies" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "slug" varchar UNIQUE,
  "logo" varchar,
  "website" varchar,
  "industry" varchar,
  "company_size" int,
  "country" varchar,
  "city" varchar,
  "description" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "categories" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "slug" varchar UNIQUE,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "jobs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_id" bigint,
  "category_id" bigint,
  "title" varchar,
  "description" text,
  "employment_type" "EmploymentType",
  "experience_level" "ExperienceLevel",
  "salary_min" decimal,
  "salary_max" decimal,
  "location" varchar,
  "is_remote" boolean,
  "deadline" date,
  "status" "JobStatus",
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "applications" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "job_id" bigint,
  "candidate_profile_id" bigint,
  "cover_letter" text,
  "status" "ApplicationStatus",
  "applied_at" timestamp,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "skills" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "candidate_skill" (
  "candidate_profile_id" bigint,
  "skill_id" bigint,
  PRIMARY KEY ("candidate_profile_id", "skill_id")
);

COMMENT ON TABLE "candidate_skill" IS 'Composite Primary Key';

ALTER TABLE "candidate_profiles" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "employer_profiles" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "employer_profiles" ADD FOREIGN KEY ("company_id") REFERENCES "companies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "jobs" ADD FOREIGN KEY ("company_id") REFERENCES "companies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "jobs" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "applications" ADD FOREIGN KEY ("job_id") REFERENCES "jobs" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "applications" ADD FOREIGN KEY ("candidate_profile_id") REFERENCES "candidate_profiles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "candidate_skill" ADD FOREIGN KEY ("candidate_profile_id") REFERENCES "candidate_profiles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "candidate_skill" ADD FOREIGN KEY ("skill_id") REFERENCES "skills" ("id") DEFERRABLE INITIALLY IMMEDIATE;
